# Generated by Django 4.2.5 on 2024-06-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_profile_auth_token_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
