# Generated by Django 4.2.5 on 2024-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='This is the best vendor', null=True),
        ),
    ]
